# Use Ubuntu como imagen base
FROM ubuntu:20.04

# Actualiza e instala las dependencias necesarias, incluyendo Python y MongoDB
RUN apt-get update && apt-get install -y python3 python3-pip mongodb

# Instala Gunicorn
RUN pip3 install waitress

# Copia la aplicación y los archivos de configuración
COPY . /app

# Copia requirements.txt al contenedor
COPY requirements.txt /app/requirements.txt

# Instala las dependencias desde requirements.txt
RUN pip3 install --upgrade pip
RUN pip3 install -r /app/requirements.txt

# Configura el directorio de datos de MongoDB
RUN mkdir -p /data/db

# Define un comando de inicio personalizado que ejecute MongoDB y tu aplicación Python con Gunicorn
CMD ["sh", "-c", "mongod --bind_ip localhost & python3 -m waitress --host=0.0.0.0 --port=80 app.app:app"]

# Expone el puerto 80 dentro del contenedor
EXPOSE 5000
EXPOSE 80
EXPOSE 27017
